### ISSUE TITLE
Allow users to rename Articles, Categories, and Snippets

### ISSUE THREAD

**Issue by MarquisLP** [averi-studios/world-scribe-2-desktop#1]
**Is your feature request related to a problem? Please describe, and include issue number if applicable.**

We've all had those moments where we come up with a cool name for our new Article/Category/Snippet... only to come up with an even cooler one down the line. Right now, the app doesn't let users rename Articles, Categories,  or Snippets. (Worlds can be renamed by renaming their corresponding folder in file explorer.)

**Describe the solution you'd like**

The server will need new API routes for modifying the names of Articles, Categories, and Snippets.

On the app side, the Article page, Category detail page, and Edit Snippet page will both need a 'Rename' button somewhere. Clicking on it should reveal a control/dialog/etc. that prompts for a name and then sends it to one of the aforementioned API routes.

**Describe alternatives you've considered**

A workaround is to delete the Article/Category/Snippet and recreate it with the new name. But obviously, this could mean redoing a lot of work.

**Comment by mmoio** [comment]
@MarquisLP can i take this? It seems a good first issue

**Comment by MarquisLP** [comment]
Sure! I've assigned you to this Issue. If you have questions about anything in the code, please let me know here :)

**Comment by MarquisLP** [comment]
Oops -- I had forgotten to include Categories as a data entity that can be renamed. Implementing it should be largely the same as for Articles and Snippets. I've updated the issue's title and description to reflect this.
